#Tool hardness configuration in format 'toolname:hardness'. Higher hardness = can mine harder blocks.
toolHardness = ["minecraft:wooden_pickaxe:2.1", "minecraft:stone_pickaxe:3.5", "minecraft:iron_pickaxe:5.0", "minecraft:golden_pickaxe:2.1", "minecraft:diamond_pickaxe:60.0", "minecraft:netherite_pickaxe:110.0", "minecraft:wooden_axe:2.1", "minecraft:stone_axe:3.5", "minecraft:iron_axe:5.0", "minecraft:golden_axe:2.1", "minecraft:diamond_axe:60.0", "minecraft:netherite_axe:110.0", "minecraft:wooden_shovel:2.1", "minecraft:stone_shovel:3.5", "minecraft:iron_shovel:5.0", "minecraft:golden_shovel:2.1", "minecraft:diamond_shovel:60.0", "minecraft:netherite_shovel:110.0", "minecraft:wooden_hoe:2.1", "minecraft:stone_hoe:3.5", "minecraft:iron_hoe:5.0", "minecraft:golden_hoe:2.1", "minecraft:diamond_hoe:60.0", "minecraft:netherite_hoe:110.0", "minecraft:wooden_sword:1.0", "minecraft:stone_sword:1.7", "minecraft:iron_sword:2.5", "minecraft:golden_sword:1.0", "minecraft:diamond_sword:30.0", "minecraft:netherite_sword:55.0"]
#Default hardness for tools not specified in the config
#Range: 0.1 ~ 100.0
defaultHardness = 1.0
#Multiplier for tool hardness to determine maximum block hardness that can be mined. If block hardness > tool hardness * this multiplier, the block cannot be mined.
#Range: 0.1 ~ 10.0
hardnessMultiplier = 1.0
#Enable drop control based on tool hardness. If disabled, blocks will always drop items regardless of tool hardness.
enableDropControl = true
#Enable tool damage when trying to mine blocks that are too hard for the tool. Tool will lose 1 durability per second.
enableToolDamageOnInvalidMining = true
#Tool hardness ratio threshold below which tools will take damage. Lower values mean tools take damage only when severely inadequate.
#Range: 0.01 ~ 1.0
toolDamageHardnessThreshold = 0.1
#Enable mining speed modification based on surrounding identical blocks.
enableSurroundingBlocksModifier = true
#Minimum speed multiplier when surrounded by many identical blocks.
#Range: 0.001 ~ 1.0
minSpeedMultiplier = 0.05
#Maximum speed multiplier when no identical blocks are around.
#Range: 1.0 ~ 5.0
maxSpeedMultiplier = 1.0
#Speed curve type: 'linear' or 'logarithmic'
speedCurveType = "logarithmic"
#Automatically detect and assign hardness values to tools based on their vanilla tier levels.
autoDetectToolHardness = true
#Enable mining speed penalty based on tool durability wear. More damaged tools mine slower.
enableDurabilitySpeedPenalty = true
#Enable tool hardness penalty based on tool durability wear. More damaged tools can't mine as hard blocks.
enableDurabilityHardnessPenalty = true
#Maximum speed penalty for completely worn tools (0.0 = no penalty, 0.9 = 90% speed reduction)
#Range: 0.0 ~ 1.0
maxDurabilitySpeedPenalty = 0.5
#Maximum hardness penalty for completely worn tools (0.0 = no penalty, 0.9 = 90% hardness reduction)
#Range: 0.0 ~ 1.0
maxDurabilityHardnessPenalty = 0.32
#Durability penalty curve type: 'linear', 'quadratic', or 'exponential'
durabilityPenaltyCurve = "quadratic"
#Enable mining speed penalty when using wrong tool type for a block (e.g., using pickaxe on dirt)
enableWrongToolPenalty = true
#Speed penalty when using wrong tool type (0.0 = no penalty, 0.5 = 50% speed reduction)
#Range: 0.0 ~ 1.0
wrongToolSpeedPenalty = 0.5
#Bypass vanilla tool type restrictions and always use the tool's actual mining speed, regardless of tool correctness
bypassVanillaToolRestrictions = true
#Use custom speed calculation based on hardness ratio instead of vanilla speed calculation
useCustomSpeedCalculation = true
#Speed calculation method: 
# - 'linear': Speed proportional to hardness ratio (simple and predictable)
# - 'inverse': Speed inversely proportional to block hardness (realistic but can be extreme)
# - 'logarithmic': Logarithmic growth (smooth progression, good balance)
# - 'exponential': Exponential growth when ratio > 1 (rewards high-tier tools)
# - 'quadratic': Quadratic curve (smooth penalty for low ratios, moderate boost for high ratios)
speedCalculationMethod = "logarithmic"
#Base mining speed for custom calculation (blocks per second)
#Range: 0.1 ~ 50.0
baseMiningSpeed = 5.0
#Maximum speed multiplier for custom calculation when tool hardness greatly exceeds block hardness
#Range: 1.0 ~ 10.0
maxSpeedMultiplierCustom = 3.0
#Enable slow mining without drops when tool hardness is insufficient but within tolerance range
enableSlowMiningWithoutDrops = true
#Hardness multiplier for slow mining without drops. Blocks with hardness between tool_hardness * hardnessMultiplier and tool_hardness * slowMiningHardnessMultiplier can be broken slowly without drops.
#Range: 1.0 ~ 10.0
slowMiningHardnessMultiplier = 2.0
#Speed penalty for slow mining without drops (0.0 = no penalty, 0.9 = 90% speed reduction)
#Range: 0.0 ~ 1.0
slowMiningSpeedPenalty = 0.8
#Enable debug logging for BetterExcavate mod. When disabled, all logs are suppressed for better performance.
enableDebugLogging = false

